@extends('layouts.app', ['title' => 'Dashboard | Web Kompresi'])

@php use App\Support\Format; @endphp

@section('content')
    <section class="page-head">
        <div>
            <p class="eyebrow">Dashboard</p>
            <h1>Library media kamu</h1>
            <p class="page-copy">Semua upload, hasil kompresi, dan ukuran storage kita rangkum di sini.</p>
        </div>

        <a href="{{ route('files.create') }}" class="button button--primary">Upload file</a>
    </section>

    <section class="stats-grid">
        <article class="stat-card">
            <span>Total files</span>
            <strong>{{ $stats['total_files'] }}</strong>
            <small>{{ Format::bytes($stats['total_storage']) }} total storage</small>
        </article>
        <article class="stat-card">
            <span>Video</span>
            <strong>{{ $stats['video_files'] }}</strong>
            <small>Original media</small>
        </article>
        <article class="stat-card">
            <span>Audio</span>
            <strong>{{ $stats['audio_files'] }}</strong>
            <small>Original media</small>
        </article>
        <article class="stat-card">
            <span>Compressed output</span>
            <strong>{{ Format::bytes($stats['compressed_size']) }}</strong>
            <small>Generated by ffmpeg jobs</small>
        </article>
    </section>

    <section class="section-card">
        <div class="section-card__header">
            <div>
                <h2>Recent files</h2>
                <p>{{ $files->total() }} file tercatat untuk akun ini.</p>
            </div>
        </div>

        @if ($files->isEmpty())
            <div class="empty-state">
                <h3>Belum ada file</h3>
                <p>Mulai dengan upload audio atau video pertama kamu.</p>
                <a href="{{ route('files.create') }}" class="button button--primary">Upload sekarang</a>
            </div>
        @else
            <div class="file-grid">
                @foreach ($files as $file)
                    <a href="{{ route('files.show', $file) }}" class="file-card">
                        <div class="file-card__row">
                            <div>
                                <div class="file-card__type">{{ Format::fileTypeIcon($file->type) }}</div>
                                <h3>{{ $file->name }}</h3>
                                <p>{{ strtoupper($file->type) }} · {{ Format::bytes($file->size) }}</p>
                            </div>
                            <span class="badge badge--{{ $file->status }}">{{ $file->status }}</span>
                        </div>

                        <div class="file-card__meta">
                            <span>{{ $file->compressions_count }} compression</span>
                            <span>{{ Format::duration($file->duration) }}</span>
                            <span>{{ Format::date($file->created_at) }}</span>
                        </div>
                    </a>
                @endforeach
            </div>

            <div class="pagination-wrap">
                {{ $files->links() }}
            </div>
        @endif
    </section>
@endsection
